### PR TITLE
Update to new stateless callbacks.

### PR DESCRIPTION
**Pull request by iphydf**

### CODE REVIEW

**Comment by iphydf** [comment]
FYI: this won't build quite yet with the current tox library. I just made this PR to make you aware of the changes.

For discussions, join `#toktok` on freenode.

**Comment by abbat** [comment]
This breaks compilation with original toxcore. Forked toxcore needs define to support both versions like this:

``` c
#ifndef FORKED_TOXCORE
    tox_iterate(self->tox);
#else
    tox_iterate(self->tox, self);
#endif
```

P.S. Also removing additional parameter from callback in forked toxcore breaks logic :(

**Comment by iphydf** [comment]
What logic does it break? To me it looked like pytoxcore passes the same `self` to every callback. Is that not the case?

**Comment by abbat** [comment]
`self` is a pointer to PyObject (class in python script). Without it I have to write global map to connect toxcore object to appropriate python object to emit event in callback. Or I don't understand this changes.

**Comment by iphydf** [comment]
The change is that instead of passing it to every callback, you pass it to `tox_iterate` on every iteration. If the `self` that you pass to the callbacks is the same as in the iterate method, then the change is exactly as in this PR.

**Comment by abbat** [comment]
Ah... Understand now.

**Pull request closed without merging**
